list:
	cat Makefile

p1:		# Part 1
	clear
	dotnet build /p:StartupObject=AdventOfCode2020.Part1
	cs exe

p2:		# Part 2
	clear
	dotnet build /p:StartupObject=AdventOfCode2020.Part2
	cs exe

ite:	# Itertools example
	clear
	dotnet build /p:StartupObject=AdventOfCode2020.ExampleItertools
	cs exe

clean:
	dotnet clean
